In [ ]:
import numpy as np #guna untuk menyediakan fungsi yang siap pakai untuk memudahkan kita melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya
import pandas as pd #guna untuk membaca nama file dari csv atau txt lainnya
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier#Untuk menggunakan KNN
from sklearn.model_selection import train_test_split #digunakan untuk proses training dan testing merupakan kumpulan data yang berbeda.
from sklearn.metrics import confusion_matrix #memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh sistem (model) dengan hasil klasifikasi sebenarnya.
from sklearn.metrics import classification_report # Memberikan Report
from sklearn.metrics import accuracy_score #memberikan skor akurasi
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset = pd.read_csv('spek_hp.csv')
dataset

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,rating,kelayakan
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,1412,3476,12,7,2,0,1,0,4,1
1,2,841,1,0.5,1,4,1,61,0.8,191,...,857,3895,6,0,7,1,0,0,5,1
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,1366,2396,17,10,10,0,1,1,5,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,1752,3893,10,0,7,1,1,0,5,1
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,810,1773,15,8,7,1,0,1,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1700,1,1.9,0,0,1,54,0.5,170,...,913,2121,14,8,15,1,1,0,5,1
996,997,609,0,1.8,1,0,0,13,0.9,186,...,1632,1933,8,1,19,0,1,1,3,0
997,998,1185,0,1.4,0,1,1,8,0.5,80,...,825,1223,5,0,14,1,0,0,2,0
998,999,1533,1,0.5,1,0,0,50,0.4,171,...,832,2509,15,11,6,0,1,0,4,1
999,1000,1270,1,0.5,0,4,1,35,0.1,140,...,608,2828,9,2,3,1,0,1,4,1

Mengambil feature yang dibutuhkan agar dapat diperoleh goalsnya

In [ ]:
dataset_baru = dataset.loc[:, ['clock_speed','int_memory','n_cores','ram','rating','kelayakan']]
dataset_baru

     clock_speed  int_memory  n_cores   ram  rating  kelayakan
0            1.8           5        3  3476       4          1
1            0.5          61        5  3895       5          1
2            2.8          27        3  2396       5          1
3            0.5          25        8  3893       5          1
4            1.4          49        6  1773       4          1
..           ...         ...      ...   ...     ...        ...
995          1.9          54        7  2121       5          1
996          1.8          13        4  1933       3          0
997          1.4           8        1  1223       2          0
998          0.5          50        2  2509       4          1
999          0.5          35        6  2828       4          1

[1000 rows x 6 columns]

Mengecek data apabila ada yang kosong atau nan

In [ ]:
dataset_baru.isnull().sum()

clock_speed    0
int_memory     0
n_cores        0
ram            0
rating         0
kelayakan      0
dtype: int64

info() digunakan untuk mengetahui data type dari feature

In [ ]:
dataset_baru.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   clock_speed  1000 non-null   float64
 1   int_memory   1000 non-null   int64
 2   n_cores      1000 non-null   int64
 3   ram          1000 non-null   int64
 4   rating       1000 non-null   int64
 5   kelayakan    1000 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 47.0 KB

Memisahkan data training dan test sebesar 0.2 atau 20%

In [ ]:
x = dataset_baru[['clock_speed','int_memory','n_cores','ram','rating']]
y = dataset_baru[['kelayakan']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1)

In [ ]:
print('x_train = ',x_train.shape)
print('x_test = ',x_test.shape)
print('y_train = ',y_train.shape)
print('y_test = ',y_test.shape)

x_train =  (800, 5)
x_test =  (200, 5)
y_train =  (800, 1)
y_test =  (200, 1)

In [ ]:
print(x_train)
print(x_test)

     clock_speed  int_memory  n_cores   ram  rating
382          0.7          12        2  3445       4
994          1.4          46        2   684       4
982          0.5          47        4  3918       5
47           0.7          13        4  2617       4
521          1.0          33        1  3402       4
..           ...         ...      ...   ...     ...
767          2.3          42        4   763       4
72           1.2          40        3  2734       4
908          2.6          22        4  1852       5
235          1.5          43        1   853       4
37           0.6          28        6  1786       3

[800 rows x 5 columns]
     clock_speed  int_memory  n_cores   ram  rating
507          2.0          31        5  3989       5
818          0.8          24        5   522       3
452          1.1          24        2  3260       4
368          1.4          33        4  1471       4
242          2.4          27        1   502       4
..           ...         ...      ...   ...     ...
430          1.0          49        2  1313       4
874          1.1          34        3  1749       4
550          1.3          24        2  3733       5
608          0.5          16        3  1021       2
207          0.5          61        7  1061       5

[200 rows x 5 columns]